package envfile

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseStandard(t *testing.T) {
	content := "DB_HOST=localhost\nDB_PORT=5432\n"
	entries := ParseString(content)
	if len(entries) != 2 {
		t.Fatalf("expected 2 entries, got %d", len(entries))
	}
	if entries[0].Key != "DB_HOST" || entries[0].Value != "localhost" {
		t.Fatalf("unexpected entry: %+v", entries[0])
	}
	if entries[1].Key != "DB_PORT" || entries[1].Value != "5432" {
		t.Fatalf("unexpected entry: %+v", entries[1])
	}
}

func TestParseQuotedValues(t *testing.T) {
	content := `DB_PASS="my secret password"
OTHER='single quoted'
`
	entries := ParseString(content)
	if entries[0].Value != "my secret password" {
		t.Fatalf("expected quoted value, got %q", entries[0].Value)
	}
	if entries[1].Value != "single quoted" {
		t.Fatalf("expected single quoted value, got %q", entries[1].Value)
	}
}

func TestParseInlineComments(t *testing.T) {
	content := "STRIPE_KEY=sk_123 # get from 1Password\n"
	entries := ParseString(content)
	if entries[0].Key != "STRIPE_KEY" || entries[0].Value != "sk_123" {
		t.Fatalf("unexpected key/value: %+v", entries[0])
	}
	if entries[0].InlineComment != "get from 1Password" {
		t.Fatalf("expected inline comment, got %q", entries[0].InlineComment)
	}
}

func TestParseCommentsAndEmptyLines(t *testing.T) {
	content := "# This is a comment\n\nKEY=value\n"
	entries := ParseString(content)
	if len(entries) != 3 {
		t.Fatalf("expected 3 entries, got %d", len(entries))
	}
	if !entries[0].IsComment {
		t.Fatal("expected comment")
	}
	if !entries[1].IsEmpty {
		t.Fatal("expected empty")
	}
}

func TestDetectEnvFiles(t *testing.T) {
	dir := t.TempDir()
	// Create test files
	for _, name := range []string{".env", ".env.prod", ".env.staging", ".env.example", ".env.template", ".env.sample"} {
		os.WriteFile(filepath.Join(dir, name), []byte("KEY=val"), 0644)
	}

	files, err := DetectEnvFiles(dir)
	if err != nil {
		t.Fatal(err)
	}

	if len(files) != 3 {
		t.Fatalf("expected 3 files (excluding example/template/sample), got %d: %v", len(files), files)
	}
}

func TestEnvName(t *testing.T) {
	tests := []struct {
		path string
		want string
	}{
		{".env", "default"},
		{".env.prod", "prod"},
		{".env.staging", "staging"},
		{"/path/to/.env", "default"},
		{"/path/to/.env.local", "local"},
	}
	for _, tt := range tests {
		got := EnvName(tt.path)
		if got != tt.want {
			t.Errorf("EnvName(%q) = %q, want %q", tt.path, got, tt.want)
		}
	}
}

func TestEnvFileName(t *testing.T) {
	if EnvFileName("default") != ".env" {
		t.Fatal("expected .env for default")
	}
	if EnvFileName("prod") != ".env.prod" {
		t.Fatal("expected .env.prod for prod")
	}
}

func TestGenerateExample(t *testing.T) {
	entries := []Entry{
		{Key: "DB_HOST", Value: "localhost"},
		{Key: "STRIPE_KEY", Value: "sk_123", InlineComment: "get from 1Password"},
		{IsComment: true, RawLine: "# Database"},
		{IsEmpty: true},
	}
	example := GenerateExample(entries)
	if !contains(example, "DB_HOST=") {
		t.Fatal("expected DB_HOST= in example")
	}
	if contains(example, "localhost") {
		t.Fatal("example should not contain values")
	}
	if !contains(example, "# get from 1Password") {
		t.Fatal("expected inline comment preserved")
	}
	if !contains(example, "Auto-generated by dotlock") {
		t.Fatal("expected header")
	}
}

func contains(s, substr string) bool {
	return len(s) >= len(substr) && searchString(s, substr)
}

func searchString(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
