package envfile

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Entry represents a single line in a .env file.
type Entry struct {
	Key           string
	Value         string
	InlineComment string // comment after value, e.g. "# get from 1Password"
	RawLine       string // original line for non-KV lines (comments, empty)
	IsComment     bool
	IsEmpty       bool
}

// Parse reads and parses a .env file, returning entries preserving order.
func Parse(path string) ([]Entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening %s: %w", path, err)
	}
	defer f.Close()

	var entries []Entry
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		entries = append(entries, parseLine(line))
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	return entries, nil
}

// ParseString parses .env content from a string.
func ParseString(content string) []Entry {
	var entries []Entry
	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		entries = append(entries, parseLine(scanner.Text()))
	}
	return entries
}

func parseLine(line string) Entry {
	trimmed := strings.TrimSpace(line)

	if trimmed == "" {
		return Entry{RawLine: line, IsEmpty: true}
	}
	if strings.HasPrefix(trimmed, "#") {
		return Entry{RawLine: line, IsComment: true}
	}

	idx := strings.Index(trimmed, "=")
	if idx < 0 {
		return Entry{RawLine: line, IsComment: true} // treat malformed as comment
	}

	key := strings.TrimSpace(trimmed[:idx])
	rest := trimmed[idx+1:]

	var value, inlineComment string
	rest = strings.TrimSpace(rest)

	if len(rest) > 0 && (rest[0] == '"' || rest[0] == '\'') {
		quote := rest[0]
		endIdx := strings.IndexByte(rest[1:], quote)
		if endIdx >= 0 {
			value = rest[1 : endIdx+1]
			after := strings.TrimSpace(rest[endIdx+2:])
			if strings.HasPrefix(after, "#") {
				inlineComment = strings.TrimSpace(after[1:])
			}
		} else {
			value = rest // no closing quote, take as-is
		}
	} else {
		// Unquoted value — look for inline comment
		parts := strings.SplitN(rest, " #", 2)
		value = strings.TrimSpace(parts[0])
		if len(parts) > 1 {
			inlineComment = strings.TrimSpace(parts[1])
		}
	}

	return Entry{Key: key, Value: value, InlineComment: inlineComment}
}

// Write writes entries to a .env file.
func Write(path string, entries []Entry) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	for _, e := range entries {
		if e.IsEmpty {
			fmt.Fprintln(w)
			continue
		}
		if e.IsComment {
			fmt.Fprintln(w, e.RawLine)
			continue
		}
		line := fmt.Sprintf("%s=%s", e.Key, e.Value)
		if e.InlineComment != "" {
			line += " # " + e.InlineComment
		}
		fmt.Fprintln(w, line)
	}
	return w.Flush()
}

// WriteString formats entries as .env content string.
func WriteString(entries []Entry) string {
	var b strings.Builder
	for _, e := range entries {
		if e.IsEmpty {
			b.WriteString("\n")
			continue
		}
		if e.IsComment {
			b.WriteString(e.RawLine + "\n")
			continue
		}
		line := fmt.Sprintf("%s=%s", e.Key, e.Value)
		if e.InlineComment != "" {
			line += " # " + e.InlineComment
		}
		b.WriteString(line + "\n")
	}
	return b.String()
}

// GenerateExample generates .env.example content with keys only.
func GenerateExample(entries []Entry) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by dotlock. DO NOT EDIT.\n")
	b.WriteString("# Copy this to .env and fill in your values.\n\n")
	for _, e := range entries {
		if e.IsEmpty {
			b.WriteString("\n")
			continue
		}
		if e.IsComment {
			b.WriteString(e.RawLine + "\n")
			continue
		}
		line := e.Key + "="
		if e.InlineComment != "" {
			line += " # " + e.InlineComment
		}
		b.WriteString(line + "\n")
	}
	return b.String()
}

// excludedSuffixes lists file suffixes that should not be detected as env files.
var excludedSuffixes = []string{".example", ".template", ".sample"}

// DetectEnvFiles returns paths of .env* files in the given directory, excluding templates.
func DetectEnvFiles(dir string) ([]string, error) {
	matches, err := filepath.Glob(filepath.Join(dir, ".env*"))
	if err != nil {
		return nil, fmt.Errorf("globbing env files: %w", err)
	}

	var result []string
	for _, m := range matches {
		base := filepath.Base(m)
		excluded := false
		for _, suffix := range excludedSuffixes {
			if strings.HasSuffix(base, suffix) {
				excluded = true
				break
			}
		}
		if !excluded {
			result = append(result, m)
		}
	}
	return result, nil
}

// EnvName maps a .env file path to an environment name.
// .env → "default", .env.prod → "prod"
func EnvName(path string) string {
	base := filepath.Base(path)
	if base == ".env" {
		return "default"
	}
	return strings.TrimPrefix(base, ".env.")
}

// EnvFileName maps an environment name back to a .env file name.
// "default" → ".env", "prod" → ".env.prod"
func EnvFileName(name string) string {
	if name == "default" {
		return ".env"
	}
	return ".env." + name
}
